### ISSUE TITLE
About CapsuleConv, FullyConnected layers.

### ISSUE THREAD

**Issue by kazaros91** [andyweizhao/capsule_text_classification#14]
Hello, 
I was interested to read the paper. 
I would like to clarify the following.
Even though 
vec_transformationByMat supposed to be used in the layers according to the paper, in the code   vec_transformationByConv is applied
instead. It seems that vec_trandformationByMat is never used in the code.
Thanks in advance.

**Comment by andyweizhao** [comment]
Thank you for your interest. From our experiments, we found vec_transformationByMat slightly outperforms vec_transformationByConv. To take into computation efficiency account, vec_transformationByConv is provided in the releasing code.
