### ISSUE TITLE
What is leaky-softmax

### ISSUE THREAD

**Issue by InsaneLife** [andyweizhao/capsule_text_classification#15]
hello, I have read your paper, but I do not understand  leaky-softmax. 
Can you give me equation, thanks !

**Comment by andyweizhao** [comment]
It is a tricky function. The probability for each class will get decreased or leaked if one additional dummy-class is considered.  This function will be working for the case where one primary capsule is noisy and it doesn't contribute to any capsules in the subsequent layers.

**Comment by InsaneLife** [comment]
Thanks,  Is that 
$c_{ij} = \frac{exp(b_{ij})}{\sum_k exp(b_{ik}) + 1}$

**Comment by andyweizhao** [comment]
Correct.
