### ISSUE TITLE
For a single label task, how do you handle the output of the model ?

### ISSUE THREAD

**Issue by Mr-jxd** [andyweizhao/capsule_text_classification#18]
您好，在您的代码中在多标签数据上实验，模型输出的胶囊向量模大于0.5的标签设置为1，这样的设置很显然不适用于单标签的任务，我想知道对于单标签任务您是如何设置输出的？非常期待您的回答，感谢！

**Comment by andyweizhao** [comment]
For single label classification, we yield the label with the highest probability over the entire label set for each instance.
