### ISSUE TITLE
layer.py 101行 的 激活函数怎么理解？

### ISSUE THREAD

**Issue by JianFeiWang** [andyweizhao/capsule_text_classification#20]
感谢您的分享，我在学习代码时有一处不理解，如下：
        beta_a = _get_weights_wrapper(
                        name='beta_a', shape=[1, shape[-1]]
                    ) 
         activations = K.sqrt(K.sum(K.square(poses), axis=-1)) + beta_a 
我理解activations指的是vector的强度， 那beta_a是一个随机生成的变量，为什么要加在activations中呢？
还望请您有时间指点一下~

**Comment by andyweizhao** [comment]
Thank you for your interest. The activation in capsules_init combines the Euclidean norm of vector and a bias term learned from supervision to increase the stability of routing. Of course, it will break the value constraints ranged from 0 to 1, meaning that we cannot add a bias term in fc_layer.

**Comment by JianFeiWang** [comment]
谢谢回复。
我在更改模型capsule的维度时，将16维修改为8维，显存占用反而上升了？
![image](https://user-images.githubusercontent.com/17420821/65832136-d1b87300-e2f2-11e9-8f60-20408fc3178d.png)
