### ISSUE TITLE
Orphan Category 

### ISSUE THREAD

**Issue by JianFeiWang** [andyweizhao/capsule_text_classification#21]
在一些任务上，直接跑capsnet，相比于textcnn效果会差一些，考虑到background-noise的影响，您提出了3种策略，包括Orphan Category，Leaky-Softmax，和Coefficients Amendment。代码中好像只有Coefficients Amendment部分代码。请问其他两种方法的代码您还会更新上来吗？

**Comment by andyweizhao** [comment]
Hi Jianfei,

The codes for orphan category and leaky-softmax are included in this repo. See the line from 26 to 31 in the layer.py for leaky-softmax and check with args.use_orphan in the main.py for enabling orphan category. 

I will tentatively close this issue. Please feel free to ask additional questions.
