### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by zxs1995** [andyweizhao/capsule_text_classification#3]
您好，
![image](https://user-images.githubusercontent.com/26573634/45928435-12f6a400-bf76-11e8-87c6-32656260d6e2.png)请问您的这部分什么意思呢，hk_offsets和wk_offsets分别代表什么呢，谢谢~

**Comment by andyweizhao** [comment]
Thank you for your interest. hk_offsets and wk_offsets preserve the offset of height and width while sliding windows across the convolutional capsule layer.

**Comment by andyweizhao** [comment]
Thank you for your interest. hk_offsets and wk_offsets preserve the offsets of height and width while sliding windows are across the convolutional capsule layer.

**Comment by dongcin** [comment]
不太理解，为什么这样操作，能解释一下原因吗，谢谢

**Comment by dongcin** [comment]
@andyweizhao
