### ISSUE TITLE
为什么我得不到你论文里面的结果？

### ISSUE THREAD

**Issue by Mr-jxd** [andyweizhao/capsule_text_classification#8]
为什么我得不到你论文里面的结果？而且最终结果一直不会收敛，你是取得最大值作为最终结果吗？或者是你修改了一些超参数，可以交流一下吗？谢谢

**Comment by andyweizhao** [comment]
We observe the accuracy and loss in the validation set for the early stopping. This repository we provide includes the experimental but all of the core codes, and we will update the implementation details soon.

**Comment by andyweizhao** [comment]
Thank you for your interest. We observe the accuracy and loss in the validation set for the early stopping. This repository we provide includes the experimental but all of the core codes, and we will update the implementation details soon.
